apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jknzv61ga-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jknzv61ga-nodejs 
  name: jknzv61ga-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jknzv61ga-nodejs 
